name: CI
true:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build frontend test image
      run: docker build -f ./client/Dockerfile.dev -t restlin1212/multi_docker_test_project
        .
    - name: run frontend tests
      run: docker run -e CI=true restlin1212/multi_docker_test_project npm test
    - name: build production images
      run: 'docker build -t restlin1212/multi_docker_test_project_client ./client

        docker build -t restlin1212/multi_docker_test_project_nginx ./nginx

        docker build -t restlin1212/multi_docker_test_project_server ./server

        docker build -t restlin1212/multi_docker_test_project_worker ./worker

        '
    - name: Login to the docker CLI
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_ID}}"
        --password-stdin
    - name: Push production images to the docker hub
      run: 'docker push restlin1212/multi_docker_test_project_client

        docker push restlin1212/multi_docker_test_project_nginx

        docker push restlin1212/multi_docker_test_project_server

        docker push restlin1212/multi_docker_test_project_worker

        '
    - name: Generate deployment zip package
      run: zip -r deploy.zip . -x '*.git*'
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v17
      with:
        application_name: multi_docker_test_project
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        deployment_package: deploy.zip
        environment_name: Multidockertestproject-env
        region: us-east-2
        version_label: 3
        wait_for_environment_recovery: 120
